#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SWITCHES")]
	public partial class SwitchesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SwitchesDataContext() : 
				base(global::ConsoleApp1.Properties.Settings.Default.SWITCHESConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SwitchesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SwitchesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SwitchesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SwitchesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SWITCHTABLE> SWITCHTABLEs
		{
			get
			{
				return this.GetTable<SWITCHTABLE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSwitchState")]
		public ISingleResult<GetSwitchStateResult> GetSwitchState([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TEST", DbType="Int")] System.Nullable<int> tEST)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tEST);
			return ((ISingleResult<GetSwitchStateResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SWITCHTABLE")]
	public partial class SWITCHTABLE
	{
		
		private System.Nullable<int> _ROOM1;
		
		private System.Nullable<int> _ROOM2;
		
		public SWITCHTABLE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM1", DbType="Int")]
		public System.Nullable<int> ROOM1
		{
			get
			{
				return this._ROOM1;
			}
			set
			{
				if ((this._ROOM1 != value))
				{
					this._ROOM1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM2", DbType="Int")]
		public System.Nullable<int> ROOM2
		{
			get
			{
				return this._ROOM2;
			}
			set
			{
				if ((this._ROOM2 != value))
				{
					this._ROOM2 = value;
				}
			}
		}
	}
	
	public partial class GetSwitchStateResult
	{
		
		private System.Nullable<int> _ROOM1;
		
		private System.Nullable<int> _ROOM2;
		
		public GetSwitchStateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM1", DbType="Int")]
		public System.Nullable<int> ROOM1
		{
			get
			{
				return this._ROOM1;
			}
			set
			{
				if ((this._ROOM1 != value))
				{
					this._ROOM1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM2", DbType="Int")]
		public System.Nullable<int> ROOM2
		{
			get
			{
				return this._ROOM2;
			}
			set
			{
				if ((this._ROOM2 != value))
				{
					this._ROOM2 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
